name: bmi_voice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  mockito: ^5.4.5
  animated_bottom_navigation_bar: ^1.4.0
  audioplayers: ^6.4.0
  flutter_tts: ^4.2.2
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  syncfusion_flutter_gauges: ^23.2.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter:
  assets:
    - assets/icon.png
    - assets/sounds/start_beep.mp3
    - assets/sounds/end_beep.mp3
    - assets/sounds/error_beep.mp3
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

names_launcher:
  name: "BMI Voice"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
